{% set name = "libxc" %}
{% set version = "5.0.0" %}
{% set sha256 = "b4206940db57ba4ddb9cb635fd852914c8dd045cb07bab32427013e3ab294f4f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/libxc/libxc/-/archive/{{ version }}/libxc-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('libxc', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [not win]
    - libtool                    # [not win]
    - automake                   # [not win]
    - cmake                      # [win]
    - ninja                      # [win]

test:
  commands:
    - test -L $PREFIX/lib/libxc$SHLIB_EXT                   # [unix]
    - ldd -v $PREFIX/lib/libxc$SHLIB_EXT                    # [linux]
    - otool -L $PREFIX/lib/libxc$SHLIB_EXT                  # [osx]
    - dir "%PREFIX%\Library"                                # [win]
    - dir "%PREFIX%"\Library\include                        # [win]
    - if not exist "%PREFIX%"\Library\include\xc.h  exit 1  # [win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - conda inspect linkages --show-files --groupby=dependency libxc

about:
  home: http://www.tddft.org/programs/Libxc
  dev_url: https://gitlab.com/libxc/libxc
  doc_url: https://gitlab.com/libxc/libxc/wikis/Manual-4.0
  license: MPL-2.0
  license_url: https://opensource.org/licenses/MPL-2.0
  license_file: COPYING
  license_family: Other
  summary: M.A.L. Marques's exchange-correlation functionals for density-functional theory

extra:
  recipe-maintainers:
    - bjodah
    - jan-janssen
