travis:
  secure:
    BINSTAR_TOKEN: Vw6f99QShCyqacYv/kJlxJS0q/u5YfjozAZf4oxvRMsgfrWPmrDixCkdes2RIvken7exiAmPMuHUObvBYd/HwSpvvwptSKjNCyDBlU5LI9sSlIslb2fHuH/V873iBnOqfd0FhmI+o2nJNvnxCSjZGlDtI9qIo22AIYf4l6aP3PqfdkhCTK5CXcHg1vwPkFIeQnKc373/lq3D08McitRn8BaO5s15/HWKv2SOQGOyS9YI9J7Kujt/okxBj8v3pTPVL1f+jQzLyw0qJkK2voXWgjBFfDyZoAMcLIfyDk7i9m5ozDwG/mBKjt3+XVwIrvch03koW3y8UQiksbrdbowsmj12J32eKcIi3+/C/OQmDPNuN37binI54LpEfCx3HqHiRKGw0BTDyQGYhDkJfu63f/c54cxjfvX7al8t2X4QOXrZZXHLIVLDBjynfYF0eQaN4dh3YiHC9AMqhwFXVcd/N6UeVCKbSK7pSMGgc9NKKMrORZTZ8TAMTXuzdXp1E2ISz3zLwnivwfcMuznfFUIqBntxsTTPr1vu21nn4iDmGi/DNj7AUsVdfAoN5NXsGp4HipFCGvT0JnleFqQri+6eNnU+WDGa9+FE181hpjbL0rSHL6EbN+dWRN8esYgPvmK2VM2kwtkahgLa84W4UaC8bpF7DyWkmKjaWxzKsyxM32w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
